// Generated by FreshWDL Layout Editor. Hand-edits will be overwritten
// next time you re-export from the editor.
//
// Combined layout + manifest. Defines:
//   1. Layout-specific CSS (grid + per-widget slot placement).
//   2. The DOM (data-widget="<id>" placeholders matched by LayoutMount).
//   3. The widget manifest (constructor + enabled flag + per-widget config).
//   4. window.app, which body onload will start().

document.write('\
    <style>\
        .widgetSlot { display: flex; align-items: center; justify-content: center; overflow: hidden; min-width: 0; min-height: 0; }\
        .widgetSlot > canvas { display: block; }\
        .widgetSlot > .OuterCanvasDiv { display: block; width: 100%; height: 100%; }\
        .widgetSlot > .OuterCanvasDiv > canvas { display: block; width: 100%; }\
\
        #FWDLcontainer {\
            display: grid;\
            grid-template-columns: repeat(24, 1fr);\
            grid-template-rows: repeat(24, 1fr);\
            width: 100%;\
            height: 95vh;\
            margin: auto;\
        }\
\
        #bottom { width: 100%; height: 5vh; display: flex; }\
        #bottom .buttons { flex: 1; }\
\
        #FWDLcontainer > .widgetSlot[data-widget="temperatureBar"] { grid-column: 1 / 4; grid-row: 1 / 9; }\
        #FWDLcontainer > .widgetSlot[data-widget="temperatureBar2"] { grid-column: 5 / 8; grid-row: 1 / 9; }\
        #FWDLcontainer > .widgetSlot[data-widget="barometer"] { grid-column: 9 / 11; grid-row: 1 / 4; }\
        #FWDLcontainer > .widgetSlot[data-widget="solarBar"] { grid-column: 6 / 8; grid-row: 10 / 16; }\
        #FWDLcontainer > .widgetSlot[data-widget="status"] { grid-column: 13 / 25; grid-row: 1 / 5; }\
        #FWDLcontainer > .widgetSlot[data-widget="mainChart"] { grid-column: 13 / 25; grid-row: 6 / 15; }\
        #FWDLcontainer > .widgetSlot[data-widget="mainChart2"] { grid-column: 13 / 25; grid-row: 16 / 25; }\
        #FWDLcontainer > .widgetSlot[data-widget="windSpeed"] { grid-column: 9 / 13; grid-row: 6 / 12; }\
        #FWDLcontainer > .widgetSlot[data-widget="barometer2"] { grid-column: 9 / 13; grid-row: 13 / 19; }\
        #FWDLcontainer > .widgetSlot[data-widget="uVBar"] { grid-column: 1 / 3; grid-row: 10 / 16; }\
        #FWDLcontainer > .widgetSlot[data-widget="solarBar2"] { grid-column: 3 / 6; grid-row: 10 / 17; }\
        #FWDLcontainer > .widgetSlot[data-widget="moonSun"] { grid-column: 1 / 5; grid-row: 17 / 21; }\
        #FWDLcontainer > .widgetSlot[data-widget="uniBar"] { grid-column: 6 / 7; grid-row: 18 / 24; }\
        #FWDLcontainer > .widgetSlot[data-widget="titleRainfall"] { grid-column: 8 / 13; grid-row: 20 / 22; }\
    </style>\
    <div id="FWDLcontainer">\
        <div data-widget="temperatureBar" class="widgetSlot"></div>\
        <div data-widget="temperatureBar2" class="widgetSlot"></div>\
        <div data-widget="barometer" class="widgetSlot"></div>\
        <div data-widget="solarBar" class="widgetSlot"></div>\
        <div data-widget="status" class="widgetSlot"></div>\
        <div data-widget="mainChart" class="widgetSlot chartSlot"></div>\
        <div data-widget="mainChart2" class="widgetSlot chartSlot"></div>\
        <div data-widget="windSpeed" class="widgetSlot"></div>\
        <div data-widget="barometer2" class="widgetSlot"></div>\
        <div data-widget="uVBar" class="widgetSlot"></div>\
        <div data-widget="solarBar2" class="widgetSlot"></div>\
        <div data-widget="moonSun" class="widgetSlot"></div>\
        <div data-widget="uniBar" class="widgetSlot"></div>\
        <div data-widget="titleRainfall" class="widgetSlot"></div>\
        <div id="forecastText" style="overflow: hidden; position: absolute; opacity: 0;"></div>\
    </div>\
    <div id="bottom" class="widgetContainer">\
        <button style="display: none;" id="AltitudeButton" class="buttons"></button>\
        <button id="PressureButton" class="buttons"></button>\
        <button id="WindButton" class="buttons"></button>\
        <button id="RainfallButton" class="buttons"></button>\
        <button id="TempButton" class="buttons"></button>\
        <button id="RecordsButton" class="buttons"></button>\
        <button id="GraphsButton" class="buttons"></button>\
    </div>\
    <div id="Version" style="float: right; font-size: 0.8em;"><p>Generated by FreshWDL Layout Editor</p></div>\
');

(function (global) {
    var manifest = [
        {
            id: "buttons",
            Ctor: ButtonsHandler,
            config: {}
        },
        {
            id: "modalHandler",
            Ctor: ModalHandler,
            enabledKey: "modalHandler",
            config: {}
        },
        {
            id: "temperatureBar",
            Ctor: TemperatureBarWidget,
            enabledKey: "temperature",
            canvasID: "TempBar01",
            config: {
                canvasID: "TempBar01",
                widgetListKey: "temperature",
                withArrow: true,
                withAutoSwitch: false,
                bindings: { temp: "clientraw[4]", high: "clientraw[46]", low: "clientraw[47]", trend: "clientraw[143]" }
            }
        },
        {
            id: "temperatureBar2",
            Ctor: TemperatureBarWidget,
            enabledKey: "temperature",
            canvasID: "TempBar02",
            config: {
                canvasID: "TempBar02",
                widgetListKey: "temperature",
                withArrow: true,
                withAutoSwitch: false,
                bindings: { temp: "clientraw[4]", high: "clientraw[46]", low: "clientraw[47]", trend: "clientraw[143]" }
            }
        },
        {
            id: "barometer",
            Ctor: BarometerWidget,
            enabledKey: "barometer",
            canvasID: "Barometer01",
            config: {
                canvasID: "Barometer01",
                bindings: { pressure: "clientraw[6]", trend: "clientraw[50]" }
            }
        },
        {
            id: "solarBar",
            Ctor: SolarBarWidget,
            enabledKey: "solar",
            canvasID: "SolarBar01",
            config: {
                canvasID: "SolarBar01",
                bindings: { percent: "clientraw[34]", watts: "clientraw[127]", sunHours: "clientrawExtra[696]" }
            }
        },
        {
            id: "status",
            Ctor: StatusWidget,
            enabledKey: "status",
            canvasID: "Status01",
            config: {
                canvasID: "Status01",
                bindings: { status: "clientraw[49]", stationTime: "clientraw[32]", stationDate: "clientraw[74]" }
            }
        },
        {
            id: "forecast",
            Ctor: ForecastHandler,
            enabledKey: "forecastHandler",
            config: {
                elementId: "forecastText"
            }
        },
        {
            id: "records",
            Ctor: RecordsHandler,
            enabledKey: "recordHandler",
            config: {}
        },
        {
            id: "modalGraph",
            Ctor: ModalGraphHandler,
            enabledKey: "graphHandler",
            config: {}
        },
        {
            id: "mainChart",
            Ctor: MainChartWidget,
            enabledKey: "graphHandlerTemperature",
            canvasID: "ChartCanvas01",
            config: {
                canvasID: "ChartCanvas01",
                graphType: "bar",
                defaultBase: "rainfallBar",
                defaultRange: "hourlyDay"
            }
        },
        {
            id: "mainChart2",
            Ctor: MainChartWidget,
            enabledKey: "graphHandlerTemperature",
            canvasID: "ChartCanvas02",
            config: {
                canvasID: "ChartCanvas02",
                graphType: "line",
                defaultBase: "windSpeed",
                defaultRange: "dailyYear"
            }
        },
        {
            id: "windSpeed",
            Ctor: WindSpeedWidget,
            enabledKey: "windSpeed",
            canvasID: "WindSpeed01",
            config: {
                canvasID: "WindSpeed01",
                bindings: { speed: "clientraw[1]", gust: "clientraw[2]", windHigh: "clientraw[113]", gustHigh: "clientraw[71]" }
            }
        },
        {
            id: "barometer2",
            Ctor: BarometerWidget,
            enabledKey: "barometer",
            canvasID: "Barometer02",
            config: {
                canvasID: "Barometer02",
                bindings: { pressure: "clientraw[6]", trend: "clientraw[50]" }
            }
        },
        {
            id: "uVBar",
            Ctor: UVBarWidget,
            enabledKey: "UV",
            canvasID: "UVBar01",
            config: {
                canvasID: "UVBar01",
                bindings: { uv: "clientraw[79]" }
            }
        },
        {
            id: "solarBar2",
            Ctor: SolarBarWidget,
            enabledKey: "solar",
            canvasID: "SolarBar02",
            config: {
                canvasID: "SolarBar02",
                bindings: { percent: "clientraw[37]", watts: "clientraw[130]", sunHours: "clientrawExtra[696]" }
            }
        },
        {
            id: "moonSun",
            Ctor: MoonSunWidget,
            enabledKey: "moonSun",
            canvasID: "MoonSun01",
            config: {
                canvasID: "MoonSun01",
                bindings: { sunRise: "clientrawExtra[556]", sunSet: "clientrawExtra[557]", moonRise: "clientrawExtra[558]", moonSet: "clientrawExtra[559]", moonPhase: "clientrawExtra[560]", moonAge: "clientrawExtra[561]" }
            }
        },
        {
            id: "uniBar",
            Ctor: UniBarWidget,
            enabledKey: "rainfallDay",
            canvasID: "UniBar01",
            config: {
                canvasID: "UniBar01",
                title: useDict("rainfallDailyTitle"),
                bindings: { value: "clientraw[7]" }
            }
        },
        {
            id: "titleRainfall",
            Ctor: TitleRainfallWidget,
            enabledKey: "rainfallTitle",
            canvasID: "TitleRainfall01",
            config: {
                canvasID: "TitleRainfall01"
            }
        }
    ];

    global.app = new App({
        manifest: manifest,
        runDataManager: true,
        runTicker: true
    });
}(window));
