// LayoutDoc → Layout.js source string. Structurally matches the existing
// hand-written Layout.js: document.write(<style+DOM>) + manifest IIFE.

import { coerceDictOrText, getCatalogEntry, getPlacedWidgets } from "../catalog";
import type { ButtonConfig, LayoutDoc, WidgetInstance } from "../model/types";

const cr = (i: number) => `clientraw[${i}]`;

export function emitLayoutJs(doc: LayoutDoc): string {
  const styleBlock = emitStyle(doc);
  const domBlock = emitDom(doc);
  const manifest = emitManifest(doc);

  return [
    "// Generated by FreshWDL Layout Editor. Hand-edits will be overwritten",
    "// next time you re-export from the editor.",
    "",
    "document.write('\\",
    foldForDocWrite(escapeForDocWrite(styleBlock + domBlock)),
    "');",
    "",
    manifest,
    "",
  ].join("\n");
}

// ---------------- CSS ----------------

function emitStyle(doc: LayoutDoc): string {
  const { cols, rows } = doc.grid;
  const widgetSlots = getPlacedWidgets(doc.widgets);

  const slotRules = widgetSlots.map((w) => {
    const a = w.area;
    return `        #FWDLcontainer > .widgetSlot[data-widget="${w.instanceId}"] { grid-column: ${a.colStart} / ${a.colEnd}; grid-row: ${a.rowStart} / ${a.rowEnd}; }`;
  }).join("\n");

  return [
    "    <style>",
    "        .widgetSlot { display: flex; align-items: center; justify-content: center; overflow: hidden; min-width: 0; min-height: 0; }",
    "        .widgetSlot > canvas { display: block; }",
    "        .widgetSlot > .OuterCanvasDiv { display: block; width: 100%; height: 100%; }",
    "        .widgetSlot > .OuterCanvasDiv > canvas { display: block; width: 100%; }",
    "",
    "        /* 16:9 grid with square cells. cols / rows ≈ 16/9, so each cell is",
    "           equal in width and height — slot ratio = rowSpan / colSpan, which",
    "           lets locked-aspect widgets match their natural shape. */",
    "        #FWDLcontainer {",
    "            display: grid;",
    `            grid-template-columns: repeat(${cols}, 1fr);`,
    `            grid-template-rows: repeat(${rows}, 1fr);`,
    "            aspect-ratio: 16 / 9;",
    "            width: min(100vw, calc(95vh * 16 / 9));",
    "            margin: 0 auto;",
    "        }",
    "",
    "        #bottom { width: 100%; height: 5vh; display: flex; }",
    "        #bottom .buttons { flex: 1; }",
    "",
    slotRules,
    "    </style>",
    "",
  ].join("\n");
}

// ---------------- DOM ----------------

function emitDom(doc: LayoutDoc): string {
  const widgetSlots = getPlacedWidgets(doc.widgets);

  const slotMarkup = widgetSlots.map((w) => {
    // The MainChartWidget references an outer wrapping div in the existing
    // CSS; LayoutMount handles that automatically. Slot is identical here.
    const extraClass = w.type === "MainChartWidget" ? " chartSlot" : "";
    if (w.type === "ForecastHandler") {
      // ForecastHandler.resize() sizes #forecastText off its parentElement,
      // so #forecastText must be nested inside the slot (not be the slot
      // itself). Otherwise its parent is #FWDLcontainer and it overflows.
      const elementId = String(w.options.elementId ?? "forecastText");
      return `        <div data-widget="${w.instanceId}" class="widgetSlot"><div id="${elementId}" style="overflow: hidden;"></div></div>`;
    }
    return `        <div data-widget="${w.instanceId}" class="widgetSlot${extraClass}"></div>`;
  }).join("\n");

  const buttons = emitButtons(doc.buttons);

  return [
    '    <div id="FWDLcontainer">',
    slotMarkup,
    "    </div>",
    '    <div id="bottom" class="widgetContainer">',
    buttons,
    "    </div>",
    '    <div id="Version" style="float: right; font-size: 0.8em;"><p>Generated by FreshWDL Layout Editor</p></div>',
  ].filter(Boolean).join("\n");
}

function emitButtons(buttons: ButtonConfig[]): string {
  return buttons.map((b) => {
    const style = b.visible ? "" : ' style="display: none;"';
    return `        <button${style} id="${b.id}" class="buttons"></button>`;
  }).join("\n");
}

// ---------------- Manifest IIFE ----------------

function emitManifest(doc: LayoutDoc): string {
  const entries = doc.widgets.map(emitManifestEntry).join(",\n");
  return [
    "(function (global) {",
    "    var manifest = [",
    entries,
    "    ];",
    "",
    "    global.app = new App({",
    "        manifest: manifest,",
    "        runDataManager: true,",
    "        runTicker: true",
    "    });",
    "}(window));",
  ].join("\n");
}

function emitManifestEntry(w: WidgetInstance): string {
  const entry = getCatalogEntry(w.type);
  if (!entry) return `        /* unknown widget type: ${w.type} */`;

  const lines: string[] = [];
  lines.push(`            id: ${jsString(w.instanceId)}`);
  lines.push(`            Ctor: ${entry.ctor}`);
  if (w.enabledKey) {
    lines.push(`            enabledKey: ${jsString(w.enabledKey)}`);
  }
  if (entry.needsCanvas && w.canvasID) {
    lines.push(`            canvasID: ${jsString(w.canvasID)}`);
  }

  const cfg = emitConfig(w, entry);
  lines.push(`            config: ${cfg}`);

  return "        {\n" + lines.join(",\n") + "\n        }";
}

function emitConfig(w: WidgetInstance, entry: ReturnType<typeof getCatalogEntry>): string {
  if (!entry) return "{}";
  const parts: string[] = [];

  if (entry.needsCanvas && w.canvasID) {
    parts.push(`canvasID: ${jsString(w.canvasID)}`);
  }

  // WidgetText "withBackground" is an editor-only flag: it expands into a
  // rounded-rect <shape> prepended to the template (same panel used by
  // BarometerWidget / MoonSunWidget). The flag itself is never emitted.
  let optionValues = w.options;
  if (entry.type === "WidgetText" && w.options.withBackground) {
    const tpl = String(w.options.template ?? "");
    const bg =
      '<shape type="roundedRect" x="5%" y="5%" w="90%" h="90%"' +
      ' radius="10%" strokeSize="2.5%" fill="#F6F6F6"/>';
    optionValues = { ...w.options, template: tpl ? bg + "\n" + tpl : bg };
  }

  // Catalog-defined options (booleans/strings/numbers/selects/textareas).
  for (const opt of entry.options) {
    if (opt.key === "withBackground") continue;
    const v = optionValues[opt.key];
    if (v === undefined || v === null || v === "") continue;
    if (opt.type === "dictOrText") {
      // Dict mode → emit useDict("<key>"); literal mode → plain string.
      const dt = coerceDictOrText(v, { mode: "dict", value: "" });
      if (!dt.value) continue;
      parts.push(`${opt.key}: ${dt.mode === "dict" ? `useDict(${jsString(dt.value)})` : jsString(dt.value)}`);
      continue;
    }
    if (opt.key === "elementId" && typeof v === "string") {
      parts.push(`elementId: ${jsString(v)}`);
      continue;
    }
    if (opt.type === "boolean") parts.push(`${opt.key}: ${v ? "true" : "false"}`);
    else if (opt.type === "number") parts.push(`${opt.key}: ${Number(v)}`);
    else if (opt.type === "textarea") parts.push(`${opt.key}: ${jsBacktickString(String(v))}`);
    else parts.push(`${opt.key}: ${jsString(String(v))}`);
  }

  // windChill auto-switch boilerplate. Triggered by withAutoSwitch=true on a
  // TemperatureBarWidget. Emits the canonical dataFn + titleSource +
  // tooltipSource + autoSwitchBindings used by the existing layout.
  const isAutoSwitch = entry.type === "TemperatureBarWidget" && w.options.withAutoSwitch === true;

  // Bindings (or dataFn replacement for auto-switch).
  if (!isAutoSwitch) {
    const keys = entry.dynamicBindings
      ? Object.keys(w.bindings)
      : entry.bindings.map((f) => f.key);
    const bparts: string[] = [];
    for (const k of keys) {
      const spec = w.bindings[k];
      if (!spec) continue;
      bparts.push(`${k}: ${jsString(spec)}`);
    }
    if (bparts.length) {
      parts.push(`bindings: { ${bparts.join(", ")} }`);
    }
  }

  if (isAutoSwitch) {
    parts.push(`titleSource: { mode: "dict", modeMap: { windchill: "windchillTitle", heatIndex: "heatIndexTitle" } }`);
    parts.push(`tooltipSource: { mode: "dict", modeMap: { windchill: "windchillDescription", heatIndex: "heatIndexDescription" } }`);
    parts.push(`dataFn: function () {
                var isWC = (widgetList.windChill.mode === "windchill");
                return [
                    isWC ? arrayClientraw[44] : arrayClientraw[112],
                    isWC ? arrayClientraw[77] : arrayClientraw[110],
                    isWC ? arrayClientraw[78] : arrayClientraw[111]
                ];
            }`);
    parts.push(`autoSwitchBindings: {
                realTemp: ${jsString(cr(4))},
                realMax:  ${jsString(cr(47))},
                realMin:  ${jsString(cr(46))},
                chillMax: ${jsString(cr(78))},
                chillMin: ${jsString(cr(77))},
                heatMax:  ${jsString(cr(111))},
                heatMin:  ${jsString(cr(110))}
            }`);
  }

  if (parts.length === 0) return "{}";
  return "{\n                " + parts.join(",\n                ") + "\n            }";
}

// ---------------- helpers ----------------

function jsString(s: string): string {
  return '"' + s
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\n/g, "\\n")
    .replace(/\r/g, "\\r") + '"';
}

// Multi-line string literal using backticks. Preserves real newlines, which
// is much easier to read than `"line\n…"` in an exported Layout.js.
function jsBacktickString(s: string): string {
  return "`" + s
    .replace(/\\/g, "\\\\")
    .replace(/`/g, "\\`")
    .replace(/\$\{/g, "\\${") + "`";
}

// document.write requires backslash-newline continuations and escaped quotes.
function escapeForDocWrite(html: string): string {
  return html
    .replace(/'/g, "\\'");
}

// Fold a multi-line HTML/CSS string into a JS string literal continuation.
// Every line — including the last — gets a trailing backslash, so the line
// terminator before the closing `');` is also escaped. Without this, JS
// reports "string literal contains an unescaped line break".
function foldForDocWrite(s: string): string {
  return s.split("\n").map((l) => l + "\\").join("\n");
}
