// LayoutDoc → Layout.js source string. Structurally matches the existing
// hand-written Layout.js: document.write(<style+DOM>) + manifest IIFE.

import { coerceDictOrText, getCatalogEntry, getPlacedWidgets } from "../catalog";
import type { ButtonConfig, LayoutDoc, WidgetInstance } from "../model/types";

export function emitLayoutJs(doc: LayoutDoc): string {
  const styleBlock = emitStyle(doc);
  const domBlock = emitDom(doc);
  const manifest = emitManifest(doc);

  return [
    "// Generated by FreshWDL Layout Editor. Hand-edits will be overwritten",
    "// next time you re-export from the editor.",
    "",
    `document.write('${escapeForDocWrite(styleBlock + domBlock)}');`,
    "",
    manifest,
    "",
  ].join("\n");
}

// ---------------- CSS ----------------

function emitStyle(doc: LayoutDoc): string {
  const { cols, rows } = doc.grid;
  const widgetSlots = getPlacedWidgets(doc.widgets);

  const slotRules = widgetSlots.map((w) => {
    const a = w.area;
    return `        #FWDLcontainer > .widgetSlot[data-widget="${w.instanceId}"] { grid-column: ${a.colStart} / ${a.colEnd}; grid-row: ${a.rowStart} / ${a.rowEnd}; }`;
  }).join("\n");

  return [
    "    <style>",
    "        .widgetSlot { display: flex; align-items: center; justify-content: center; overflow: hidden; min-width: 0; min-height: 0; }",
    "        .widgetSlot > canvas { display: block; }",
    "        .widgetSlot > .OuterCanvasDiv { display: block; width: 100%; height: 100%; }",
    "        .widgetSlot > .OuterCanvasDiv > canvas { display: block; width: 100%; }",
    "",
    "        /* 16:9 grid with square cells. cols / rows ≈ 16/9, so each cell is",
    "           equal in width and height — slot ratio = rowSpan / colSpan, which",
    "           lets locked-aspect widgets match their natural shape. */",
    "        #FWDLcontainer {",
    "            display: grid;",
    `            grid-template-columns: repeat(${cols}, 1fr);`,
    `            grid-template-rows: repeat(${rows}, 1fr);`,
    "            aspect-ratio: 16 / 9;",
    "            width: min(100vw, calc(95vh * 16 / 9));",
    "            margin: 0 auto;",
    "        }",
    "",
    "        #bottom { width: 100%; height: 5vh; display: flex; }",
    "        #bottom .buttons { flex: 1; }",
    "",
    slotRules,
    "    </style>",
    "",
  ].join("\n");
}

// ---------------- DOM ----------------

// ForecastHandler is special-cased: its resize() reads dimensions off the
// slot's child #forecastText, so that inner div must exist before initialize().
export function emitSlotHtml(w: WidgetInstance, indent: string = ""): string {
  const extraClass = w.type === "MainChartWidget" ? " chartSlot" : "";
  if (w.type === "ForecastHandler") {
    const elementId = String(w.options.elementId ?? "forecastText");
    return `${indent}<div data-widget="${w.instanceId}" class="widgetSlot"><div id="${elementId}" style="overflow: hidden;"></div></div>`;
  }
  return `${indent}<div data-widget="${w.instanceId}" class="widgetSlot${extraClass}"></div>`;
}

export function emitManifestEntrySource(w: WidgetInstance): string {
  return emitManifestEntry(w).trim();
}

function emitDom(doc: LayoutDoc): string {
  const widgetSlots = getPlacedWidgets(doc.widgets);

  const slotMarkup = widgetSlots.map((w) => emitSlotHtml(w, "        ")).join("\n");

  const buttons = emitButtons(doc.buttons);

  return [
    '    <div id="FWDLcontainer">',
    slotMarkup,
    "    </div>",
    '    <div id="bottom" class="widgetContainer">',
    buttons,
    "    </div>",
    '    <div id="Version" style="float: right; font-size: 0.8em;"><p>Generated by FreshWDL Layout Editor</p></div>',
  ].filter(Boolean).join("\n");
}

function emitButtons(buttons: ButtonConfig[]): string {
  return buttons.map((b) => {
    const style = b.visible ? "" : ' style="display: none;"';
    return `        <button${style} id="${b.id}" class="buttons"></button>`;
  }).join("\n");
}

// ---------------- Manifest IIFE ----------------

function emitManifest(doc: LayoutDoc): string {
  const entries = doc.widgets.map(emitManifestEntry).join(",\n");
  return [
    "(function (global) {",
    "    var manifest = [",
    entries,
    "    ];",
    "",
    "    global.app = new App({",
    "        manifest: manifest,",
    "        runDataManager: true,",
    "        runTicker: true",
    "    });",
    "}(window));",
  ].join("\n");
}

function emitManifestEntry(w: WidgetInstance): string {
  const entry = getCatalogEntry(w.type);
  if (!entry) return `        /* unknown widget type: ${w.type} */`;

  const lines: string[] = [];
  lines.push(`            id: ${jsString(w.instanceId)}`);
  lines.push(`            Ctor: ${entry.ctor}`);
  if (w.enabledKey) {
    lines.push(`            enabledKey: ${jsString(w.enabledKey)}`);
  }
  if (entry.needsCanvas && w.canvasID) {
    lines.push(`            canvasID: ${jsString(w.canvasID)}`);
  }

  const cfg = emitConfig(w, entry);
  lines.push(`            config: ${cfg}`);

  return "        {\n" + lines.join(",\n") + "\n        }";
}

function emitConfig(w: WidgetInstance, entry: ReturnType<typeof getCatalogEntry>): string {
  if (!entry) return "{}";
  const parts: string[] = [];

  if (entry.needsCanvas && w.canvasID) {
    parts.push(`canvasID: ${jsString(w.canvasID)}`);
  }

  // Catalog-defined options (booleans/strings/numbers/selects/textareas).
  for (const opt of entry.options) {
    const v = w.options[opt.key];
    if (v === undefined || v === null || v === "") continue;
    if (opt.type === "dictOrText") {
      // Dict mode → emit useDict("<key>"); literal mode → plain string.
      const dt = coerceDictOrText(v, { mode: "dict", value: "" });
      if (!dt.value) continue;
      parts.push(`${opt.key}: ${dt.mode === "dict" ? `useDict(${jsString(dt.value)})` : jsString(dt.value)}`);
      continue;
    }
    if (opt.key === "elementId" && typeof v === "string") {
      parts.push(`elementId: ${jsString(v)}`);
      continue;
    }
    if (opt.type === "boolean") parts.push(`${opt.key}: ${v ? "true" : "false"}`);
    else if (opt.type === "number") parts.push(`${opt.key}: ${Number(v)}`);
    else if (opt.type === "textarea") parts.push(`${opt.key}: ${jsBacktickString(String(v))}`);
    else parts.push(`${opt.key}: ${jsString(String(v))}`);
  }

  // Per-type codegen hook (e.g. windChill auto-switch boilerplate).
  const extra = entry.emitExtraConfig?.(w);
  const suppressBindings = !!extra?.suppressBindings;
  if (extra?.parts.length) parts.push(...extra.parts);

  // Bindings block (suppressed when the hook takes over, e.g. auto-switch).
  if (!suppressBindings) {
    const keys = entry.dynamicBindings
      ? Object.keys(w.bindings)
      : entry.bindings.map((f) => f.key);
    const bparts: string[] = [];
    for (const k of keys) {
      const spec = w.bindings[k];
      if (!spec) continue;
      bparts.push(`${k}: ${jsString(spec)}`);
    }
    if (bparts.length) {
      parts.push(`bindings: { ${bparts.join(", ")} }`);
    }
  }

  if (parts.length === 0) return "{}";
  return "{\n                " + parts.join(",\n                ") + "\n            }";
}

// ---------------- helpers ----------------

function jsString(s: string): string {
  return '"' + s
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\n/g, "\\n")
    .replace(/\r/g, "\\r") + '"';
}

// Multi-line string literal using backticks. Preserves real newlines, which
// is much easier to read than `"line\n…"` in an exported Layout.js.
function jsBacktickString(s: string): string {
  return "`" + s
    .replace(/\\/g, "\\\\")
    .replace(/`/g, "\\`")
    .replace(/\$\{/g, "\\${") + "`";
}

function escapeForDocWrite(html: string): string {
  return html
    .replace(/\\/g, "\\\\")
    .replace(/'/g, "\\'")
    .replace(/<\//g, "<\\/")
    .replace(/\r/g, "\\r")
    .replace(/\n/g, "\\n");
}
